FROM registry.saas.hand-china.com/tools/mysql:5.6



COPY setup.sh /mysql/setup.sh

COPY sakila-data.sql /mysql/sakila-data.sql

COPY sakila-schema.sql /mysql/sakila-schema.sql

COPY privileges.sql /mysql/privileges.sql

CMD ["sh", "/mysql/setup.sh"]