FROM registry.saas.hand-china.com/tools/javabase:0.5.0

WORKDIR /

ENV LANG C.UTF-8
ENV LANGUAGE C.UTF-8
ENV LC_ALL C.UTF-8


COPY ./exam1-0.0.1-SNAPSHOT.jar /test1.jar

CMD ["java", "-jar", "test1.jar"]