spring:
   datasource:
        driver-class-name: 'com.mysql.jdbc.Driver'
        url: 'jdbc:mysql://127.0.0.1:3306/sakila?serverTimezone=UTC&&useSSL=true'
        username: 'root'
        password: '12345'

