version: '3'

services:
   mysqls:
     restart: always
     image: mysql:test
     container_name: mysqltest
     ports: 
         - 3306:3306
     command: [
                 '--character-set-server=utf8mb4',
                 '--collation-server=utf8mb4_unicode_ci'
         ]
     environment:
           MYSQL_ROOT_PASSWORD: "12345"

   java:
      image: java:test
      container_name: javatest
      depends_on:
          - mysqls
      environment:
         IP: mysqls
         PORT: 3306
         USERNAME: root
         PASSWORD: 12345
    #   ports:
    #      - "8080:8080"
    #   expose: 
    #      - "8080"
    